[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pypointd"
version = "0.0.1"
authors = [
  { name="Biniyam Belayneh", email="biniyambelayneh376@gmail.com" },
]
description = "Python package that is used to fetch transform and visualize point cloud data from USGS amazone bucket"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/benbel376/LIDAR_ETL"
"Bug Tracker" = "https://github.com/benbel376/LIDAR_ETL/issues"