
# This is a basic workflow to run tests

name: "CI tester"

# Controls when the workflow will run
on: [push, pull_request]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # this Action should follow steps to set up Python build environment
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3
    	with:
      	  path: "docs/requirements.txt"

      # Runs a single command using the runners shell
      - name: Run tests script
        run: python tests/*.py
