# This is a basic workflow to run tests

name: "CI tester"

# Controls when the workflow will run
on: [push, pull_request]
  
jobs:
  example-1:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.7"]
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # this Action should follow steps to set up Python build environment
      - name: Install Python dependencies
        run: conda install --file docs/requirements.txt
      # Runs a single command using the runners shell
      - name: Run tests script
        run: python tests/*.py
